# theme-glass — Hyprland (sem Matugen)

general {
    col.active_border = rgba(337bccee) rgba(7bc0cdee) 45deg
    col.inactive_border = rgba(fcfffaaa)
}

decoration {
    rounding = 12

    active_opacity = 1.0
    inactive_opacity = 0.95

    shadow {
        enabled = true
        range = 14
        render_power = 3
        color = rgba(15152933)
    }

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
    }
}

group {
    col.border_active = rgba(337bccee)
    col.border_inactive = rgba(fcfffaaa)
    col.border_locked_active = rgba(7bc0cdee)
    col.border_locked_inactive = rgba(fcfffaaa)
}

# idle_inhibitor ativo ao iniciar: adicione ao hyprland.conf
# exec-once = ~/.config/custom/theme-glass/rofi/hub.sh --idle-on
