# custom — keybinds (adicionar ao hyprland.conf)
# source = ~/.config/custom/binds.conf

source = ~/.config/custom/current

$dir = ~/.config/custom/$THEME
$rofi_dir = $dir/rofi

$hub = $rofi_dir/hub.sh
$hub_gui = $rofi_dir/hub-gui.sh
$foot_cfg = ~/.config/custom/foot/foot.ini
$foot = foot -c $foot_cfg
$foot_float = foot -c $foot_cfg --app-id foot-float

$file = thunar
$browser = firefox
$shot = ~/.config/custom/scripts/shot.sh
$rofi_theme = ~/.config/custom/scripts/rofi-theme.sh

$mainMod = SUPER

###################
### CUSTOM HUB  ###
###################

bind = $mainMod, D, exec, $hub --menu
bind = $mainMod, F12, exec, $hub --waybar
bind = $mainMod, F11, exec, $hub_gui
bind = $mainMod, F10, exec, $hub --wall
bind = $mainMod, T, exec, $rofi_theme

bind = $mainMod, V, exec, $hub --clip
bind = $mainMod, X, exec, $hub --power
bind = $mainMod SHIFT, D, exec, $hub --window

bind = $mainMod SHIFT, R, exec, hyprctl reload

###################
### APPS        ###
###################

bind = $mainMod, RETURN, exec, $hub --foot
bind = $mainMod SHIFT, RETURN, exec, $foot_float
bind = $mainMod, E, exec, $file
bind = $mainMod, W, exec, $browser
bind = $mainMod, F, fullscreen, 1

###################
### SCREENSHOTS ###
###################

bind = , Print, exec, $shot --shotnow
bind = $mainMod, Print, exec, $shot --shotarea
