# theme-sonokai — Hyprland (Sonokai Maia)

general {
    col.active_border = rgba(9cd57bee) rgba(78cee9ee) 45deg
    col.inactive_border = rgba(273136aa)
}

decoration {
    rounding = 12

    active_opacity = 1.0
    inactive_opacity = 0.92

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(1c1e1fcc)
    }

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
    }
}

group {
    col.border_active = rgba(9cd57bee)
    col.border_inactive = rgba(273136aa)
    col.border_locked_active = rgba(a2e57bee)
    col.border_locked_inactive = rgba(273136aa)
}

# idle_inhibitor ativo ao iniciar: adicione ao hyprland.conf
# exec-once = ~/.config/custom/theme-sonokai/rofi/hub.sh --idle-on
