# theme-prateado — Hyprland (sem Matugen)

general {
    col.active_border = rgba(caccccee) rgba(b0b0a8ee) 45deg
    col.inactive_border = rgba(1e1e1eaa)
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.92

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(121318ee)
    }

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
    }
}

group {
    col.border_active = rgba(caccccee)
    col.border_inactive = rgba(1e1e1eaa)
    col.border_locked_active = rgba(989890ee)
    col.border_locked_inactive = rgba(1e1e1eaa)
}

# idle_inhibitor ativo ao iniciar: adicione ao hyprland.conf
# exec-once = ~/.config/custom/theme-prateado/rofi/hub.sh --idle-on
