# theme-bamboo — Hyprland (Bamboo vulgaris)

general {
    col.active_border = rgba(dbb651ee) rgba(8fb573ee) 45deg
    col.inactive_border = rgba(252623aa)
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.92

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(1c1e1bcc)
    }

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
    }
}

group {
    col.border_active = rgba(dbb651ee)
    col.border_inactive = rgba(252623aa)
    col.border_locked_active = rgba(8fb573ee)
    col.border_locked_inactive = rgba(252623aa)
}

# idle_inhibitor ativo ao iniciar: adicione ao hyprland.conf
# exec-once = ~/.config/custom/theme-bamboo/rofi/hub.sh --idle-on
