# theme-gruvbox — Hyprland (sem Matugen)

general {
    col.active_border = rgba(83a598ee) rgba(ebdbb2ee) 45deg
    col.inactive_border = rgba(282828aa)
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.92

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(1d2021ee)
    }

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
    }
}

group {
    col.border_active = rgba(83a598ee)
    col.border_inactive = rgba(282828aa)
    col.border_locked_active = rgba(b8bb26ee)
    col.border_locked_inactive = rgba(282828aa)
}

# idle_inhibitor ativo ao iniciar: adicione ao hyprland.conf
# exec-once = ~/.config/custom/theme-gruvbox/rofi/hub.sh --idle-on
